<?php
/**
 * TL_ROOT/system/modules/redirect/languages/ja/modules.php 
 * 
 * Contao extension: redirect 1.5.0 stable 
 * Japanese translation file 
 * 
 * Copyright : ©2011-2012 Jan Theofel, ©2010 ETES Gmbh, © 2008-2009 Andreas Schempp, © 2008 CustomSoft, © 2009 Thyon Design 
 * License   : LGPL 
 * Author    : Jan Theofel (jan.theofel), http://www.theofel.de/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['redirect']['0'] = "リダイレクトモジュール";
$GLOBALS['TL_LANG']['FMD']['sslRedirect']['0'] = "SSLリダイレクト";
$GLOBALS['TL_LANG']['FMD']['sslRedirect']['1'] = "このモジュールは安全なバージョン(https://)のページに移動します。";
$GLOBALS['TL_LANG']['FMD']['nonSslRedirect']['0'] = "非SSLリダイレクト";
$GLOBALS['TL_LANG']['FMD']['nonSslRedirect']['1'] = "このモジュールは安全なページにアクセスしていると、通常(安全ではない)バージョン(http://)のページに移動します。";
$GLOBALS['TL_LANG']['FMD']['loginRedirect']['0'] = "ログインしているメンバーをリダイレクト";
$GLOBALS['TL_LANG']['FMD']['loginRedirect']['1'] = "このモジュールはメンバーがログインしていると、指定したページに移動します。";
$GLOBALS['TL_LANG']['FMD']['browserRedirect']['0'] = "ブラウザー(バージョン)リダイレクト";
$GLOBALS['TL_LANG']['FMD']['browserRedirect']['1'] = "このモジュールはユーザーが使用している(設定可能な)ブラウザーやブラウザーのバージョンに応じて、指定したページに移動します。";
$GLOBALS['TL_LANG']['FMD']['osRedirect']['0'] = "OSリダイレクト";
$GLOBALS['TL_LANG']['FMD']['osRedirect']['1'] = "このモジュールはユーザーのオペレテーィングシステムに依存して、指定したページに移動します。";
