<?php
/**
 * TL_ROOT/system/modules/redirect/languages/ja/tl_module.php 
 * 
 * Contao extension: redirect 1.5.0 stable 
 * Japanese translation file 
 * 
 * Copyright : ©2011-2012 Jan Theofel, ©2010 ETES Gmbh, © 2008-2009 Andreas Schempp, © 2008 CustomSoft, © 2009 Thyon Design 
 * License   : LGPL 
 * Author    : Jan Theofel (jan.theofel), http://www.theofel.de/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['redirectDomain']['0'] = "リダイレクト先のドメイン";
$GLOBALS['TL_LANG']['tl_module']['redirectDomain']['1'] = "別のドメインにリダイレクトしたい場合は、ここにドメイン(例: ssl.example.com)を入力してください。それ以外の場合は空のままにしてください。";
$GLOBALS['TL_LANG']['tl_module']['membersOnly']['0'] = "メンバーだけ";
$GLOBALS['TL_LANG']['tl_module']['membersOnly']['1'] = "メンバーとしてログインしている場合だけ移動します。";
$GLOBALS['TL_LANG']['tl_module']['browser']['0'] = "ブラウザーを選択";
$GLOBALS['TL_LANG']['tl_module']['browser']['1'] = "以下のブラウザーから1つを選択するか、独自のブラウザーの表現を選択してテキスト入力に個別の正規表現を入力してください。";
$GLOBALS['TL_LANG']['tl_module']['browserRgxp']['0'] = "ブラウザーを検出する正規表現";
$GLOBALS['TL_LANG']['tl_module']['browserRgxp']['1'] = "独自のブラウザーの表現を選択すると、ブラウザーのHTTP_USER_AGENTの文字列を検査するための正規表現を入力できます。区切り文字も加えてください。";
$GLOBALS['TL_LANG']['tl_module']['browserCookie']['0'] = "クッキーのセット中はリダイレクトしない";
$GLOBALS['TL_LANG']['tl_module']['browserCookie']['1'] = "一度だけリダイレクトさせたい場合、対象のページでクッキーを設定します。クッキーを設定するにはce-tracking機能拡張を使用してください。";
$GLOBALS['TL_LANG']['tl_module']['browserCookieName']['0'] = "クッキーの名前";
$GLOBALS['TL_LANG']['tl_module']['browserCookieName']['1'] = "リダイレクトを防ぐクッキーの名前です。";
$GLOBALS['TL_LANG']['tl_module']['browserCookieValue']['0'] = "クッキーの値";
$GLOBALS['TL_LANG']['tl_module']['browserCookieValue']['1'] = "リダイレクトを防ぐために設定しなればならないクッキーの値です。";
$GLOBALS['TL_LANG']['tl_module']['osredirect']['0'] = "OSを選択";
$GLOBALS['TL_LANG']['tl_module']['osredirect']['1'] = "リダイレクトさせるOSを選択してください。";
$GLOBALS['TL_LANG']['tl_module']['redirectinex']['0'] = "リダイレクト先";
$GLOBALS['TL_LANG']['tl_module']['redirectinex']['1'] = "使用するリダイレクトの種類を選択してください。";
$GLOBALS['TL_LANG']['tl_module']['redirectinex']['internal'] = "内部(Contaoのページ)";
$GLOBALS['TL_LANG']['tl_module']['redirectinex']['external'] = "外部(URL)";
$GLOBALS['TL_LANG']['tl_module']['externalredirecturl']['0'] = "URL";
$GLOBALS['TL_LANG']['tl_module']['externalredirecturl']['1'] = "外部のURLを(http://... を含めて)入力してください。";
$GLOBALS['TL_LANG']['tl_module']['browserList']['custom'] = "独自のブラウザーの表現(以下を参照)";
$GLOBALS['TL_LANG']['tl_module']['browserList']['mobilecontao'] = "すべての携帯機器(Contaoのロジック)";
$GLOBALS['TL_LANG']['tl_module']['browserList']['mobile'] = "すべての携帯機器(この機能拡張のロジック)";
$GLOBALS['TL_LANG']['tl_module']['browserList']['ie'] = "Internet Explorer";
$GLOBALS['TL_LANG']['tl_module']['browserList']['iemobile'] = "IEMobile";
$GLOBALS['TL_LANG']['tl_module']['browserList']['firefox'] = "Firefox";
$GLOBALS['TL_LANG']['tl_module']['browserList']['chrome'] = "Chrome";
$GLOBALS['TL_LANG']['tl_module']['browserList']['omniweb'] = "OmniWeb";
$GLOBALS['TL_LANG']['tl_module']['browserList']['opera'] = "Opera";
$GLOBALS['TL_LANG']['tl_module']['browserList']['opera-mini'] = "Opera Mini";
$GLOBALS['TL_LANG']['tl_module']['browserList']['opera-mobile'] = "Opera Mobile";
$GLOBALS['TL_LANG']['tl_module']['browserList']['camino'] = "Camino";
$GLOBALS['TL_LANG']['tl_module']['browserList']['konqueror'] = "Konqueror";
$GLOBALS['TL_LANG']['tl_module']['browserList']['other'] = "その他";
$GLOBALS['TL_LANG']['tl_module']['browserVersionMatchList']['any'] = "任意のバージョン";
$GLOBALS['TL_LANG']['tl_module']['browserVersionMatchList']['lt'] = "より小さいバージョン";
$GLOBALS['TL_LANG']['tl_module']['browserVersionMatchList']['le'] = "以下のバージョン";
$GLOBALS['TL_LANG']['tl_module']['browserVersionMatchList']['eq'] = "等しいバージョン";
$GLOBALS['TL_LANG']['tl_module']['browserVersionMatchList']['ge'] = "以上のバージョン";
$GLOBALS['TL_LANG']['tl_module']['browserVersionMatchList']['gt'] = "より大きいバージョン";
$GLOBALS['TL_LANG']['tl_module']['osredirectList']['mac'] = "Mac OS";
$GLOBALS['TL_LANG']['tl_module']['osredirectList']['win-ce'] = "Windows mobile/CE";
$GLOBALS['TL_LANG']['tl_module']['osredirectList']['win'] = "Windows";
$GLOBALS['TL_LANG']['tl_module']['osredirectList']['ios'] = "iOS (iPhone, iPad, iPod)";
$GLOBALS['TL_LANG']['tl_module']['osredirectList']['android'] = "Android";
$GLOBALS['TL_LANG']['tl_module']['osredirectList']['blackberry'] = "Blackberry";
$GLOBALS['TL_LANG']['tl_module']['osredirectList']['symbian'] = "Symbian";
$GLOBALS['TL_LANG']['tl_module']['osredirectList']['webos'] = "WebOS";
$GLOBALS['TL_LANG']['tl_module']['osredirectList']['unix'] = "Linux, FreeBSD, OpenBSD, NetBSD";
$GLOBALS['TL_LANG']['tl_module']['osredirectList']['other'] = "その他";
